/**
 * seed-ingram.mjs
 * Seeds curated Ingram Micro products (Desktops, Laptops, Synology NAS) into Supabase.
 * Run: node seed-ingram.mjs
 * Re-running is safe — uses upsert on sku+supplier.
 */

import { createClient } from '@supabase/supabase-js'
import { config } from 'dotenv'
import { resolve, dirname } from 'path'
import { fileURLToPath } from 'url'

const __dirname = dirname(fileURLToPath(import.meta.url))
config({ path: resolve(__dirname, '.env') })

const supabase = createClient(
  process.env.SUPABASE_URL,
  process.env.SUPABASE_SERVICE_ROLE_KEY
)

const USD = 1.35
function sgd(usd) { return Math.round(usd * USD * 100) / 100 }

const PRODUCTS = [

  // ── DESKTOPS ──────────────────────────────────────────────────────────────

  {
    sku: 'IM-DELL-OPX3000-SFF',
    supplier: 'ingram',
    category: 'Desktop',
    name: 'Dell OptiPlex 3000 Small Form Factor',
    description: 'Compact business desktop with Intel Core i5-12500T, 8GB DDR4, 256GB SSD, Windows 11 Pro. Ideal for everyday office productivity with a small footprint.',
    price_usd: 749,
    partner_usd: 620,
    image_url: 'https://cdn.simpleicons.org/dell',
    stock_qty: 50,
    specs: {
      'Processor': 'Intel Core i5-12500T (6-Core, 18MB Cache, up to 4.4GHz)',
      'Memory': '8GB DDR4 3200MHz (1x 8GB, max 64GB, 2 slots)',
      'Storage': '256GB M.2 PCIe NVMe SSD',
      'Graphics': 'Intel UHD Graphics 770 (integrated)',
      'Operating System': 'Windows 11 Pro 64-bit',
      'Form Factor': 'Small Form Factor (SFF)',
      'Dimensions': '292 × 92 × 290 mm',
      'Weight': '4.6 kg',
      'Ports (Front)': '2x USB 3.2 Gen 1, 1x USB-C, 1x Universal Audio Jack',
      'Ports (Rear)': '4x USB 3.2 Gen 1, 2x USB 2.0, 1x HDMI 2.0, 1x DisplayPort 1.4, 1x RJ-45',
      'Networking': 'Intel I219-LM Gigabit Ethernet',
      'Wireless': 'Optional Wi-Fi 6 + Bluetooth 5.1',
      'Power Supply': '180W 80 PLUS Bronze',
      'Security': 'TPM 2.0, Kensington Lock, BIOS protection',
      'Warranty': '3-Year ProSupport Basic (on-site)',
    },
  },
  {
    sku: 'IM-DELL-OPX5000-TWR',
    supplier: 'ingram',
    category: 'Desktop',
    name: 'Dell OptiPlex 5000 Tower',
    description: 'Mid-range tower desktop with Intel Core i7-12700, 16GB DDR4, 512GB NVMe SSD, Windows 11 Pro. Expandable, reliable, and built for demanding workloads.',
    price_usd: 1149,
    partner_usd: 950,
    image_url: 'https://cdn.simpleicons.org/dell',
    stock_qty: 30,
    specs: {
      'Processor': 'Intel Core i7-12700 (12-Core, 25MB Cache, up to 4.9GHz)',
      'Memory': '16GB DDR4 3200MHz (2x 8GB, max 128GB, 4 slots)',
      'Storage': '512GB M.2 PCIe NVMe SSD',
      'Graphics': 'Intel UHD Graphics 770 (integrated)',
      'Operating System': 'Windows 11 Pro 64-bit',
      'Form Factor': 'Tower (MiniTower)',
      'Dimensions': '350 × 164 × 363 mm',
      'Weight': '8.1 kg',
      'Drive Bays': '1x M.2 (occupied), 1x 2.5" internal, 1x 3.5" internal',
      'Ports (Front)': '2x USB 3.2 Gen 1, 1x USB-C, 1x Universal Audio Jack',
      'Ports (Rear)': '4x USB 3.2 Gen 1, 2x USB 2.0, 2x DisplayPort 1.4, 1x HDMI 2.0, 1x RJ-45',
      'Expansion Slots': '1x PCIe 5.0 x16, 1x PCIe 4.0 x16, 1x PCIe 3.0 x1',
      'Networking': 'Intel I219-LM Gigabit Ethernet',
      'Wireless': 'Optional Wi-Fi 6 + Bluetooth 5.1',
      'Power Supply': '300W 80 PLUS Bronze',
      'Security': 'TPM 2.0, Chassis intrusion switch, Smart Card reader (optional)',
      'Warranty': '3-Year ProSupport Basic (on-site)',
    },
  },
  {
    sku: 'IM-HP-ED800G9-SFF',
    supplier: 'ingram',
    category: 'Desktop',
    name: 'HP EliteDesk 800 G9 Small Form Factor',
    description: 'Enterprise-grade compact desktop with Intel Core i5-12500, 16GB DDR5, 256GB SSD, Windows 11 Pro. HP Wolf Security built-in for hardware-level protection.',
    price_usd: 899,
    partner_usd: 745,
    image_url: 'https://cdn.simpleicons.org/hp',
    stock_qty: 40,
    specs: {
      'Processor': 'Intel Core i5-12500 (6-Core, 18MB Cache, up to 4.6GHz)',
      'Memory': '16GB DDR5 4800MHz (1x 16GB, max 64GB, 2 slots)',
      'Storage': '256GB M.2 PCIe NVMe SSD',
      'Graphics': 'Intel UHD Graphics 770 (integrated)',
      'Operating System': 'Windows 11 Pro 64-bit',
      'Form Factor': 'Small Form Factor (SFF)',
      'Dimensions': '274 × 90 × 280 mm',
      'Weight': '4.7 kg',
      'Ports (Front)': '2x USB 3.2 Gen 2 Type-A, 1x USB-C (with DisplayPort), 1x 3.5mm combo jack',
      'Ports (Rear)': '4x USB 3.2 Gen 1 Type-A, 1x USB 3.2 Gen 2 Type-C, 2x DisplayPort 1.4, 1x HDMI 2.0, 1x RJ-45',
      'Networking': 'Intel I219-LM Gigabit Ethernet',
      'Wireless': 'Wi-Fi 6E (802.11ax) + Bluetooth 5.3',
      'Power Supply': '180W 92% Efficient',
      'Security': 'HP Wolf Security, TPM 2.0, HP Sure Start, HP Sure Run',
      'Warranty': '3-Year HP Next Business Day On-site',
    },
  },
  {
    sku: 'IM-HP-PD400G9-MT',
    supplier: 'ingram',
    category: 'Desktop',
    name: 'HP ProDesk 400 G9 Microtower',
    description: 'Affordable business microtower with Intel Core i3-12100, 8GB DDR4, 256GB SSD, Windows 11 Pro. A cost-effective entry point for small business deployments.',
    price_usd: 599,
    partner_usd: 495,
    image_url: 'https://cdn.simpleicons.org/hp',
    stock_qty: 60,
    specs: {
      'Processor': 'Intel Core i3-12100 (4-Core, 12MB Cache, up to 4.3GHz)',
      'Memory': '8GB DDR4 3200MHz (1x 8GB, max 64GB, 2 slots)',
      'Storage': '256GB M.2 PCIe NVMe SSD',
      'Graphics': 'Intel UHD Graphics 730 (integrated)',
      'Operating System': 'Windows 11 Pro 64-bit',
      'Form Factor': 'Microtower',
      'Dimensions': '340 × 152 × 366 mm',
      'Weight': '6.3 kg',
      'Drive Bays': '1x M.2 (occupied), 1x 3.5" internal HDD bay',
      'Ports (Front)': '2x USB 3.2 Gen 1, 1x USB-C, 1x 3.5mm combo jack',
      'Ports (Rear)': '4x USB 3.2 Gen 1, 2x USB 2.0, 1x DisplayPort 1.4, 1x VGA, 1x RJ-45',
      'Networking': 'Realtek Gigabit Ethernet',
      'Wireless': 'Optional Wi-Fi 5 + Bluetooth 4.2',
      'Power Supply': '180W 85% Efficient',
      'Security': 'TPM 2.0, HP Sure Start Gen7, BIOS lock',
      'Warranty': '1-Year HP Next Business Day On-site',
    },
  },
  {
    sku: 'IM-LNV-M70S-G4',
    supplier: 'ingram',
    category: 'Desktop',
    name: 'Lenovo ThinkCentre M70s Gen 4 SFF',
    description: 'Slim desktop with Intel Core i5-13400, 16GB DDR4, 512GB SSD, Windows 11 Pro. Engineered for reliability with ThinkShield security and tool-free serviceability.',
    price_usd: 849,
    partner_usd: 700,
    image_url: 'https://cdn.simpleicons.org/lenovo',
    stock_qty: 35,
    specs: {
      'Processor': 'Intel Core i5-13400 (10-Core, 20MB Cache, up to 4.6GHz)',
      'Memory': '16GB DDR4 3200MHz (2x 8GB, max 64GB, 2 slots)',
      'Storage': '512GB M.2 PCIe NVMe SSD (Gen 4)',
      'Graphics': 'Intel UHD Graphics 730 (integrated)',
      'Operating System': 'Windows 11 Pro 64-bit',
      'Form Factor': 'Small Form Factor (SFF)',
      'Dimensions': '282.5 × 92.5 × 290 mm',
      'Weight': '4.8 kg',
      'Drive Bays': '1x M.2 PCIe Gen 4 (occupied), 1x 2.5" SATA',
      'Ports (Front)': '2x USB 3.2 Gen 1, 1x USB-C 3.2 Gen 1, 1x 3.5mm combo jack',
      'Ports (Rear)': '4x USB 3.2 Gen 1, 1x USB-C, 1x DisplayPort 1.4, 1x HDMI 2.1, 1x RJ-45',
      'Networking': 'Intel I219-V Gigabit Ethernet',
      'Wireless': 'Wi-Fi 6 (802.11ax) + Bluetooth 5.1',
      'Power Supply': '180W 90% Efficient',
      'Security': 'ThinkShield, TPM 2.0, Kensington Nano Lock, Chassis intrusion detection',
      'Warranty': '3-Year Lenovo Premier Support On-site',
    },
  },
  {
    sku: 'IM-LNV-M90Q-G3',
    supplier: 'ingram',
    category: 'Desktop',
    name: 'Lenovo ThinkCentre M90q Gen 3 Tiny',
    description: 'Ultra-compact enterprise desktop with Intel Core i7-12700T, 16GB DDR5, 512GB NVMe, Windows 11 Pro. 1-litre form factor, perfect for space-constrained deployments.',
    price_usd: 1099,
    partner_usd: 910,
    image_url: 'https://cdn.simpleicons.org/lenovo',
    stock_qty: 25,
    specs: {
      'Processor': 'Intel Core i7-12700T (12-Core, 25MB Cache, up to 4.7GHz)',
      'Memory': '16GB DDR5 4800MHz (2x 8GB, max 64GB, 2 slots)',
      'Storage': '512GB M.2 PCIe NVMe SSD (Gen 4)',
      'Graphics': 'Intel UHD Graphics 770 (integrated)',
      'Operating System': 'Windows 11 Pro 64-bit',
      'Form Factor': 'Tiny (1 Litre)',
      'Dimensions': '179.5 × 182.9 × 36.5 mm',
      'Weight': '1.35 kg',
      'Ports (Front)': '1x USB 3.2 Gen 1, 1x USB-C 3.2 Gen 2, 1x 3.5mm combo jack',
      'Ports (Rear)': '3x USB 3.2 Gen 1, 1x USB-C (Thunderbolt 4), 2x DisplayPort 1.4, 1x HDMI 2.1, 1x RJ-45',
      'Networking': 'Intel I219-LM Gigabit Ethernet',
      'Wireless': 'Wi-Fi 6E (802.11ax) + Bluetooth 5.2',
      'Power Supply': '135W External Adapter',
      'Security': 'ThinkShield, TPM 2.0, Smart USB Protection, BIOS Absolute Persistence',
      'Warranty': '3-Year Lenovo Premier Support On-site',
    },
  },

  // ── LAPTOPS ───────────────────────────────────────────────────────────────

  {
    sku: 'IM-DELL-LAT5540-15',
    supplier: 'ingram',
    category: 'Laptop',
    name: 'Dell Latitude 5540 15" Business Laptop',
    description: '15.6" FHD business laptop with Intel Core i5-1345U, 16GB DDR4, 512GB SSD, Windows 11 Pro. Built for professionals with long battery life and robust durability.',
    price_usd: 1099,
    partner_usd: 910,
    image_url: 'https://cdn.simpleicons.org/dell',
    stock_qty: 45,
    specs: {
      'Processor': 'Intel Core i5-1345U (10-Core, 12MB Cache, up to 4.7GHz)',
      'Memory': '16GB DDR4 3200MHz (soldered, not upgradeable)',
      'Storage': '512GB M.2 PCIe NVMe SSD',
      'Display': '15.6" FHD (1920×1080) IPS Anti-glare, 250 nits',
      'Graphics': 'Intel Iris Xe Graphics (integrated)',
      'Operating System': 'Windows 11 Pro 64-bit',
      'Battery': '54Wh, up to 14 hours (MobileMark 2018)',
      'Weight': '1.86 kg',
      'Dimensions': '357.6 × 234.5 × 18.4 mm',
      'Webcam': '720p HD with privacy shutter',
      'Keyboard': 'Backlit, spill-resistant',
      'Ports': '2x USB-C Thunderbolt 4, 2x USB 3.2 Gen 1, 1x HDMI 2.0, 1x SD card reader, 1x 3.5mm jack, 1x RJ-45',
      'Wireless': 'Wi-Fi 6E (802.11ax) + Bluetooth 5.3',
      'Security': 'Fingerprint reader, IR camera, TPM 2.0, Dell SafeScreen (optional)',
      'Certifications': 'MIL-STD-810H, EPEAT Gold',
      'Warranty': '3-Year Dell ProSupport (on-site, next business day)',
    },
  },
  {
    sku: 'IM-DELL-LAT7440-14',
    supplier: 'ingram',
    category: 'Laptop',
    name: 'Dell Latitude 7440 14" Premium Business Laptop',
    description: '14" FHD+ premium laptop with Intel Core i7-1365U, 16GB LPDDR5, 512GB SSD, Windows 11 Pro. Ultra-light at 1.26kg with up to 18 hours battery and built-in AI features.',
    price_usd: 1599,
    partner_usd: 1320,
    image_url: 'https://cdn.simpleicons.org/dell',
    stock_qty: 30,
    specs: {
      'Processor': 'Intel Core i7-1365U (10-Core, 12MB Cache, up to 5.2GHz)',
      'Memory': '16GB LPDDR5 6400MHz (soldered, not upgradeable)',
      'Storage': '512GB M.2 PCIe NVMe SSD (Gen 4)',
      'Display': '14" FHD+ (1920×1200) IPS Touch, 400 nits, 100% sRGB',
      'Graphics': 'Intel Iris Xe Graphics (integrated)',
      'Operating System': 'Windows 11 Pro 64-bit',
      'Battery': '64Wh, up to 18 hours (MobileMark 2018), ExpressCharge 2.0',
      'Weight': '1.26 kg',
      'Dimensions': '311.4 × 215.4 × 16.4 mm',
      'Webcam': '1080p FHD IR with AI auto-framing, privacy shutter',
      'Keyboard': 'Backlit, spill-resistant, AI-based noise cancellation',
      'Ports': '2x Thunderbolt 4 (USB-C), 1x USB-C 3.2, 1x USB-A 3.2, 1x HDMI 2.0, 1x microSD, 1x 3.5mm jack',
      'Wireless': 'Wi-Fi 6E (802.11ax) + Bluetooth 5.3',
      'Security': 'Fingerprint reader, IR facial recognition, TPM 2.0, ControlVault 3',
      'Certifications': 'MIL-STD-810H, EPEAT Gold, ENERGY STAR',
      'Warranty': '3-Year Dell ProSupport (on-site, next business day)',
    },
  },
  {
    sku: 'IM-HP-EB840G10-14',
    supplier: 'ingram',
    category: 'Laptop',
    name: 'HP EliteBook 840 G10 14" Laptop',
    description: '14" WUXGA laptop with Intel Core i5-1335U, 16GB DDR5, 512GB SSD, Windows 11 Pro. HP Wolf Security, Wi-Fi 6E, and a stunning IPS display for the modern enterprise.',
    price_usd: 1249,
    partner_usd: 1035,
    image_url: 'https://cdn.simpleicons.org/hp',
    stock_qty: 40,
    specs: {
      'Processor': 'Intel Core i5-1335U (10-Core, 12MB Cache, up to 4.6GHz)',
      'Memory': '16GB DDR5 5200MHz (1x 16GB, max 64GB, 2 slots — 1 soldered)',
      'Storage': '512GB M.2 PCIe NVMe SSD (Gen 4)',
      'Display': '14" WUXGA (1920×1200) IPS Anti-glare, 400 nits, 100% sRGB',
      'Graphics': 'Intel Iris Xe Graphics (integrated)',
      'Operating System': 'Windows 11 Pro 64-bit',
      'Battery': '51Wh, up to 13 hours, HP Fast Charge (50% in 30 min)',
      'Weight': '1.40 kg',
      'Dimensions': '322.7 × 223.5 × 17.9 mm',
      'Webcam': '5MP IR + 9MP world-facing camera, AI-based auto frame',
      'Keyboard': 'Backlit, spill-resistant (1.5L)',
      'Ports': '2x Thunderbolt 4 (USB-C, 40Gbps), 2x USB-A 3.2 Gen 1, 1x HDMI 2.0, 1x microSD, 1x 3.5mm jack, 1x RJ-45',
      'Wireless': 'Wi-Fi 6E (802.11ax) + Bluetooth 5.3',
      'Security': 'Fingerprint reader, IR facial recognition, TPM 2.0, HP Sure Sense, HP Wolf Security',
      'Certifications': 'MIL-STD-810H, EPEAT Gold, ENERGY STAR',
      'Warranty': '3-Year HP Care Pack On-site Next Business Day',
    },
  },
  {
    sku: 'IM-HP-PB450G10-15',
    supplier: 'ingram',
    category: 'Laptop',
    name: 'HP ProBook 450 G10 15.6" Laptop',
    description: '15.6" FHD laptop with Intel Core i5-1335U, 8GB DDR4, 256GB SSD, Windows 11 Pro. A dependable and affordable business laptop for everyday professional use.',
    price_usd: 849,
    partner_usd: 700,
    image_url: 'https://cdn.simpleicons.org/hp',
    stock_qty: 55,
    specs: {
      'Processor': 'Intel Core i5-1335U (10-Core, 12MB Cache, up to 4.6GHz)',
      'Memory': '8GB DDR4 3200MHz (1x 8GB, max 32GB, 2 slots)',
      'Storage': '256GB M.2 PCIe NVMe SSD',
      'Display': '15.6" FHD (1920×1080) IPS Anti-glare, 250 nits',
      'Graphics': 'Intel Iris Xe Graphics (integrated)',
      'Operating System': 'Windows 11 Pro 64-bit',
      'Battery': '45Wh, up to 12 hours',
      'Weight': '1.74 kg',
      'Dimensions': '357.9 × 233.9 × 19.9 mm',
      'Webcam': '720p HD with privacy shutter',
      'Keyboard': 'Backlit (optional)',
      'Ports': '1x USB-C 3.2 Gen 1 (DisplayPort 1.4), 2x USB-A 3.2 Gen 1, 1x HDMI 1.4b, 1x SD card reader, 1x 3.5mm jack, 1x RJ-45',
      'Wireless': 'Wi-Fi 6 (802.11ax) + Bluetooth 5.3',
      'Security': 'Fingerprint reader, TPM 2.0, HP Sure Start Gen7',
      'Certifications': 'MIL-STD-810H, EPEAT Silver',
      'Warranty': '1-Year HP Next Business Day On-site',
    },
  },
  {
    sku: 'IM-LNV-TP-L14-G4',
    supplier: 'ingram',
    category: 'Laptop',
    name: 'Lenovo ThinkPad L14 Gen 4 14" Laptop',
    description: '14" FHD IPS laptop with AMD Ryzen 5 PRO 7530U, 16GB DDR4, 512GB SSD, Windows 11 Pro. Military-grade durability, full-size keyboard, and wide port selection.',
    price_usd: 999,
    partner_usd: 825,
    image_url: 'https://cdn.simpleicons.org/lenovo',
    stock_qty: 40,
    specs: {
      'Processor': 'AMD Ryzen 5 PRO 7530U (6-Core, 16MB Cache, up to 4.5GHz)',
      'Memory': '16GB DDR4 3200MHz (2x 8GB, max 40GB — 8GB soldered + 1 SO-DIMM)',
      'Storage': '512GB M.2 PCIe NVMe SSD (Gen 4)',
      'Display': '14" FHD (1920×1080) IPS Anti-glare, 300 nits, 45% NTSC',
      'Graphics': 'AMD Radeon 740M (integrated)',
      'Operating System': 'Windows 11 Pro 64-bit',
      'Battery': '57Wh, up to 15 hours, Rapid Charge (80% in 1 hour)',
      'Weight': '1.62 kg',
      'Dimensions': '330.3 × 226.8 × 21.2 mm',
      'Webcam': '1080p FHD IR with ThinkShutter privacy cover',
      'Keyboard': 'Backlit, spill-resistant (1L), TrackPoint',
      'Ports': '2x USB-C 3.2 Gen 2 (one with PD + DP 1.4), 2x USB-A 3.2 Gen 1, 1x HDMI 2.0, 1x SD card reader, 1x 3.5mm jack, 1x RJ-45, 1x SIM (4G LTE optional)',
      'Wireless': 'Wi-Fi 6E (802.11ax) + Bluetooth 5.1',
      'Security': 'Fingerprint reader, IR camera, TPM 2.0, ThinkShield',
      'Certifications': 'MIL-STD-810H (12 methods), EPEAT Gold',
      'Warranty': '3-Year Lenovo Premier Support On-site',
    },
  },
  {
    sku: 'IM-LNV-TP-T14S-G4',
    supplier: 'ingram',
    category: 'Laptop',
    name: 'Lenovo ThinkPad T14s Gen 4 14" Laptop',
    description: '14" 2.8K OLED flagship business laptop with Intel Core i7-1365U, 32GB LPDDR5x, 1TB SSD, Windows 11 Pro. Premium build, ultra-thin at 1.23kg, and all-day battery.',
    price_usd: 1799,
    partner_usd: 1490,
    image_url: 'https://cdn.simpleicons.org/lenovo',
    stock_qty: 20,
    specs: {
      'Processor': 'Intel Core i7-1365U (10-Core, 12MB Cache, up to 5.2GHz)',
      'Memory': '32GB LPDDR5x 6400MHz (soldered, not upgradeable)',
      'Storage': '1TB M.2 PCIe NVMe SSD (Gen 4)',
      'Display': '14" 2.8K (2880×1800) OLED Anti-glare, 400 nits, 100% DCI-P3, Touch',
      'Graphics': 'Intel Iris Xe Graphics (integrated)',
      'Operating System': 'Windows 11 Pro 64-bit',
      'Battery': '57.5Wh, up to 15 hours, Rapid Charge 2.0 (50% in 30 min)',
      'Weight': '1.23 kg',
      'Dimensions': '317 × 226.9 × 16.9 mm',
      'Webcam': '1440p QHD IR with ThinkShutter, AI-based noise cancellation',
      'Keyboard': 'Backlit, spill-resistant (1L), TrackPoint with haptic touchpad',
      'Ports': '2x Thunderbolt 4 (USB-C, 40Gbps), 2x USB-A 3.2 Gen 1, 1x HDMI 2.0, 1x 3.5mm jack, 1x nano-SIM (4G/5G optional)',
      'Wireless': 'Wi-Fi 6E (802.11ax) + Bluetooth 5.3',
      'Security': 'Fingerprint reader, IR facial recognition, TPM 2.0, ThinkShield',
      'Certifications': 'MIL-STD-810H (12 methods), EPEAT Gold, ENERGY STAR',
      'Warranty': '3-Year Lenovo Premier Support On-site',
    },
  },

  // ── SYNOLOGY NAS ──────────────────────────────────────────────────────────

  {
    sku: 'IM-SYN-DS223-2BAY',
    supplier: 'ingram',
    category: 'NAS',
    name: 'Synology DiskStation DS223 2-Bay NAS',
    description: 'Entry-level 2-bay NAS with Realtek RTD1619B quad-core 1.7GHz, 2GB RAM, 1GbE. Perfect for home office and SOHO file sharing, backup, and media streaming.',
    price_usd: 299,
    partner_usd: 248,
    image_url: 'https://cdn.simpleicons.org/synology',
    stock_qty: 25,
    specs: {
      'Processor': 'Realtek RTD1619B Quad-Core 1.7GHz',
      'Memory': '2GB DDR4 (not expandable)',
      'Drive Bays': '2x 3.5"/2.5" SATA HDD/SSD',
      'Max Raw Capacity': 'Up to 36TB (2x 18TB drives)',
      'Network Ports': '1x RJ-45 1GbE',
      'USB Ports': '2x USB 3.2 Gen 1 (Type-A)',
      'RAID Support': 'Synology Hybrid RAID, JBOD, Basic, RAID 0, RAID 1',
      'Supported File Systems': 'Btrfs, ext4',
      'Wake-on-LAN': 'Yes',
      'Scheduled Power On/Off': 'Yes',
      'Dimensions': '165 × 108 × 232.2 mm',
      'Weight': '1.08 kg (diskless)',
      'Power Consumption': '9.45W (access), 3.88W (HDD hibernate)',
      'Fan': '1x 92mm',
      'Operating Temperature': '0°C – 40°C',
      'Warranty': '2-Year Synology Limited Warranty',
    },
  },
  {
    sku: 'IM-SYN-DS423P-4BAY',
    supplier: 'ingram',
    category: 'NAS',
    name: 'Synology DiskStation DS423+ 4-Bay NAS',
    description: '4-bay NAS with Intel Celeron J4125 quad-core, 2GB DDR4 (expandable to 6GB), 2x GbE. Ideal for small business centralised storage, backup, and collaboration.',
    price_usd: 549,
    partner_usd: 455,
    image_url: 'https://cdn.simpleicons.org/synology',
    stock_qty: 20,
    specs: {
      'Processor': 'Intel Celeron J4125 Quad-Core 2.0GHz (burst 2.7GHz)',
      'Memory': '2GB DDR4 (expandable to 6GB, 2 slots)',
      'Drive Bays': '4x 3.5"/2.5" SATA HDD/SSD',
      'M.2 NVMe Slots': 'None',
      'Max Raw Capacity': 'Up to 72TB (4x 18TB drives)',
      'Network Ports': '2x RJ-45 1GbE (Link Aggregation / Failover)',
      'USB Ports': '2x USB 3.2 Gen 1 (Type-A)',
      'RAID Support': 'SHR, JBOD, Basic, RAID 0, 1, 5, 6, 10',
      'Supported File Systems': 'Btrfs, ext4',
      'Hardware Encryption': 'AES-NI',
      'Dimensions': '166 × 199 × 223 mm',
      'Weight': '2.05 kg (diskless)',
      'Power Consumption': '30.63W (access), 8.97W (HDD hibernate)',
      'Fan': '2x 92mm',
      'Operating Temperature': '0°C – 40°C',
      'Warranty': '3-Year Synology Limited Warranty',
    },
  },
  {
    sku: 'IM-SYN-DS923P-4BAY',
    supplier: 'ingram',
    category: 'NAS',
    name: 'Synology DiskStation DS923+ 4-Bay NAS',
    description: '4-bay SMB NAS with AMD Ryzen R1600 dual-core, 4GB ECC DDR4 (expandable to 32GB), 2x GbE + 2x M.2 NVMe slots. Designed for growing teams needing reliable shared storage.',
    price_usd: 699,
    partner_usd: 579,
    image_url: 'https://cdn.simpleicons.org/synology',
    stock_qty: 15,
    specs: {
      'Processor': 'AMD Ryzen R1600 Dual-Core 2.6GHz (burst 3.1GHz)',
      'Memory': '4GB ECC DDR4 (expandable to 32GB, 2 SO-DIMM slots)',
      'Drive Bays': '4x 3.5"/2.5" SATA HDD/SSD',
      'M.2 NVMe Slots': '2x M.2 2280 NVMe SSD (for SSD cache only)',
      'Expandable With': 'Up to 9 drives with DX517 expansion unit',
      'Max Raw Capacity': '108TB + 2TB NVMe cache',
      'Network Ports': '2x RJ-45 1GbE (Link Aggregation / Failover)',
      'USB Ports': '2x USB 3.2 Gen 1 (Type-A)',
      'RAID Support': 'SHR, SHR-2, JBOD, Basic, RAID 0, 1, 5, 6, 10',
      'Hardware Encryption': 'AES-NI',
      'Supported File Systems': 'Btrfs, ext4',
      'Dimensions': '166 × 199 × 223 mm',
      'Weight': '2.24 kg (diskless)',
      'Power Consumption': '33.27W (access), 11.68W (HDD hibernate)',
      'Fan': '2x 92mm',
      'Operating Temperature': '0°C – 40°C',
      'Warranty': '3-Year Synology Limited Warranty',
    },
  },
  {
    sku: 'IM-SYN-DS1522P-5BAY',
    supplier: 'ingram',
    category: 'NAS',
    name: 'Synology DiskStation DS1522+ 5-Bay NAS',
    description: '5-bay NAS with AMD Ryzen R1600, 8GB DDR4 ECC (expandable to 32GB), 4x GbE, 2x M.2 NVMe slots. Expandable to 15 drives with DX517 expansion units.',
    price_usd: 899,
    partner_usd: 745,
    image_url: 'https://cdn.simpleicons.org/synology',
    stock_qty: 12,
    specs: {
      'Processor': 'AMD Ryzen R1600 Dual-Core 2.6GHz (burst 3.1GHz)',
      'Memory': '8GB ECC DDR4 (expandable to 32GB, 2 SO-DIMM slots)',
      'Drive Bays': '5x 3.5"/2.5" SATA HDD/SSD',
      'M.2 NVMe Slots': '2x M.2 2280 NVMe SSD (for SSD cache only)',
      'Expandable With': 'Up to 15 drives with 2x DX517 expansion units',
      'Max Raw Capacity': '270TB + NVMe cache',
      'Network Ports': '4x RJ-45 1GbE (Link Aggregation / Failover)',
      'USB Ports': '2x USB 3.2 Gen 1 (Type-A)',
      'eSATA Ports': '2x eSATA (for expansion units)',
      'RAID Support': 'SHR, SHR-2, JBOD, Basic, RAID 0, 1, 5, 6, 10',
      'Hardware Encryption': 'AES-NI',
      'Supported File Systems': 'Btrfs, ext4',
      'Dimensions': '166 × 233 × 223 mm',
      'Weight': '2.85 kg (diskless)',
      'Power Consumption': '38.4W (access), 13.5W (HDD hibernate)',
      'Fan': '2x 92mm',
      'Operating Temperature': '0°C – 40°C',
      'Warranty': '3-Year Synology Limited Warranty',
    },
  },
  {
    sku: 'IM-SYN-DS1823XS-8BAY',
    supplier: 'ingram',
    category: 'NAS',
    name: 'Synology DiskStation DS1823xs+ 8-Bay NAS',
    description: '8-bay high-performance NAS with AMD Ryzen V1780B quad-core, 8GB DDR4 ECC (expandable to 32GB), 2x 10GbE + 2x GbE. Built for enterprise-grade performance and scalability.',
    price_usd: 1699,
    partner_usd: 1409,
    image_url: 'https://cdn.simpleicons.org/synology',
    stock_qty: 8,
    specs: {
      'Processor': 'AMD Ryzen V1780B Quad-Core 3.35GHz',
      'Memory': '8GB ECC DDR4 (expandable to 32GB, 2 SO-DIMM slots)',
      'Drive Bays': '8x 3.5"/2.5" SATA HDD/SSD',
      'M.2 NVMe Slots': '2x M.2 2280 NVMe SSD (SSD cache or storage pool)',
      'Expandable With': 'Up to 18 drives with 2x DX1222 expansion units',
      'Max Raw Capacity': '324TB + NVMe cache',
      'Network Ports': '2x RJ-45 10GbE, 2x RJ-45 1GbE',
      'USB Ports': '2x USB 3.2 Gen 1 (Type-A)',
      'PCIe Slot': '1x PCIe 3.0 x8 (for 10/25GbE NIC or additional M.2 card)',
      'RAID Support': 'SHR, SHR-2, JBOD, Basic, RAID 0, 1, 5, 6, 10',
      'Hardware Encryption': 'AES-NI',
      'Supported File Systems': 'Btrfs, ext4',
      'Dimensions': '177 × 343 × 243 mm',
      'Weight': '4.48 kg (diskless)',
      'Power Consumption': '74.33W (access), 25.24W (HDD hibernate)',
      'Fan': '3x 80mm',
      'Operating Temperature': '0°C – 35°C',
      'Warranty': '3-Year Synology Limited Warranty',
    },
  },
  {
    sku: 'IM-SYN-RS1221P-RACK',
    supplier: 'ingram',
    category: 'NAS',
    name: 'Synology RackStation RS1221+ 12-Bay Rackmount NAS',
    description: '12-bay 2U rackmount NAS with AMD Ryzen V1500B quad-core, 4GB DDR4 ECC (expandable to 16GB), 4x GbE, 2x M.2 NVMe. Ideal for data centres and server room deployments.',
    price_usd: 1399,
    partner_usd: 1160,
    image_url: 'https://cdn.simpleicons.org/synology',
    stock_qty: 10,
    specs: {
      'Processor': 'AMD Ryzen V1500B Quad-Core 2.2GHz',
      'Memory': '4GB ECC DDR4 (expandable to 16GB, 4 SO-DIMM slots)',
      'Drive Bays': '12x 3.5"/2.5" SATA HDD/SSD (hot-swappable)',
      'M.2 NVMe Slots': '2x M.2 2280 NVMe SSD (for SSD cache only)',
      'Expandable With': 'Up to 36 drives with 2x RX1217 expansion units',
      'Max Raw Capacity': '648TB + NVMe cache',
      'Form Factor': '2U Rack',
      'Rack Units': '2U',
      'Network Ports': '4x RJ-45 1GbE (Link Aggregation / Failover)',
      'USB Ports': '2x USB 3.2 Gen 1 (Type-A)',
      'eSATA Ports': '2x eSATA (for expansion units)',
      'PCIe Slot': '1x PCIe 3.0 x8',
      'RAID Support': 'SHR, SHR-2, JBOD, Basic, RAID 0, 1, 5, 6, 10',
      'Hardware Encryption': 'AES-NI',
      'Supported File Systems': 'Btrfs, ext4',
      'Redundant PSU': 'Optional (RPS1300C)',
      'Dimensions': '88 × 482 × 570 mm',
      'Weight': '7.34 kg (diskless)',
      'Power Consumption': '78.01W (access), 28.49W (HDD hibernate)',
      'Operating Temperature': '0°C – 40°C',
      'Warranty': '3-Year Synology Limited Warranty',
    },
  },
]

// ─── SEED ─────────────────────────────────────────────────────────────────────

async function main() {
  console.log('=== Seeding Ingram Micro Products ===\n')

  const rows = PRODUCTS.map(p => ({
    sku: p.sku,
    supplier: p.supplier,
    category: p.category,
    name: p.name,
    description: p.description,
    price_sgd: sgd(p.price_usd),
    base_price_sgd: sgd(p.price_usd),
    partner_price_sgd: sgd(p.partner_usd),
    markup_percent: 0,
    stock_qty: p.stock_qty,
    image_url: p.image_url,
    specs: p.specs,
  }))

  const { data, error } = await supabase
    .from('products')
    .upsert(rows, { onConflict: 'sku,supplier' })
    .select('id, name')

  if (error) {
    console.error('✗ Seed failed:', error.message)
    process.exit(1)
  }

  const cats = { Desktop: 0, Laptop: 0, NAS: 0 }
  PRODUCTS.forEach(p => cats[p.category]++)

  console.log(`✓ Seeded ${data.length} products`)
  console.log(`   Desktops : ${cats.Desktop}`)
  console.log(`   Laptops  : ${cats.Laptop}`)
  console.log(`   NAS      : ${cats.NAS}`)
  console.log()
  data.forEach(p => console.log(`   · ${p.name}`))
  console.log('\nDone.')
}

main().catch(e => { console.error(e); process.exit(1) })
